import "../globals.css";
import { dir } from "i18next";

import CommonThemeProvider from "../common/contexts/theme";
import { languages } from "../i18n/settings";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: "Messadine Next Generation",
  description: "Generated by create next app",
};

import Nav from "../../components/theme-switcher";
export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body>
        <CommonThemeProvider>
          <Nav lang={lang} />
          {children}
        </CommonThemeProvider>
      </body>
    </html>
  );
}
