import CommonThemeProvider from "@/common/contexts/theme";
import "./globals.css";
import Main from '../components/theme-switcher' 
export const metadata = {
  title: "Messadine Next Generation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CommonThemeProvider>
        <Main />
          {children}</CommonThemeProvider>
      </body>
    </html>
  );
}
