import "./globals.css";

import CommonThemeProvider from "./common/contexts/theme";
export const metadata = {
  title: "Messadine Next Generation",
  description: "Generated by create next app",
};

import Nav from "../components/theme-switcher";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CommonThemeProvider>
          <Nav />
          {children}
        </CommonThemeProvider>
      </body>
    </html>
  );
}
